// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sma
NumericVector sma(NumericVector x, int n);
RcppExport SEXP _RDataScience_sma(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(sma(x, n));
    return rcpp_result_gen;
END_RCPP
}
// simple_moving_avg
NumericVector simple_moving_avg(DataFrame dt, int n);
RcppExport SEXP _RDataScience_simple_moving_avg(SEXP dtSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(simple_moving_avg(dt, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RDataScience_sma", (DL_FUNC) &_RDataScience_sma, 2},
    {"_RDataScience_simple_moving_avg", (DL_FUNC) &_RDataScience_simple_moving_avg, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RDataScience(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
